### ISSUE TITLE
When deploying code

### ISSUE THREAD

**Issue by Richard1Bob** [halleewong/ScribblePrompt#11]
Thank you blogger for your work, you do a great job. I ran into the following problems while running the code:

Traceback (most recent call last):
  File "E:\ScribblePrompt\ScribblePrompt-0.1.0\demos\app.py", line 450, in <module>
    scribble_img = gr.Image(
  File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\component_meta.py", line 167, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'brush_radius'

**Comment by halleewong** [comment]
Hi, please check you're using the right version of Gradio. The app in `demos/app.py` requires gradio 3.40.1. 

Alternatively, we have a newer gradio app on huggingface [here](https://huggingface.co/spaces/halleewong/ScribblePrompt) that uses gradio 4.41.0. You can download the code for that app in the files tab of the huggingface page

**Comment by Richard1Bob** [comment]
> Hi, please check you're using the right version of Gradio. The app in `demos/app.py` requires gradio 3.40.1.
> 
> Alternatively, we have a newer gradio app on huggingface [here](https://huggingface.co/spaces/halleewong/ScribblePrompt) that uses gradio 4.41.0. You can download the code for that app in the files tab of the huggingface page
Thanks, after your advice, I have been able to successfully deploy locally!
Now there is another question I would like to consult: when I segment my own blood vessel image, it is easy to over-segment when I use click operation, and the same situation will still occur when I click again after cancellation. How can I solve this problem?
![image](https://github.com/user-attachments/assets/384dd65b-b67f-4a7f-804d-0975cd9457dc)

**Comment by halleewong** [comment]
It looks like you are only using positive clicks here. Have you tried using negative clicks or scribbles to mark the background?
